name: Build release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v1
    - name: Build .file
      run: |
        mkdir out
        mkdir out/developer-script-es
        php update-manager/update-manager.php dscript out/dev-script/es.txt . es
        php update-manager/update-manager.php script out/es.txt "out/es.file" 8
        cd out
        zip -r developer-script.zip developer-script-es
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release_${{ github.sha }}
        release_name: ${{ github.sha }}
    - name: Upload .file
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/es.file
        asset_name: es.file
        asset_content_type: application/octet-stream
    - name: Upload dscript
      uses: actions/upload-release-asset@v1.0.1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/developer-script.zip
        asset_name: developer-script.zip
        asset_content_type: application/octet-stream
